[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "never"

[[services]]
name = "web"
source = "."

[services.web.variables]
NODE_ENV = "production" 